apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: zero-trust-wisecow
  namespace: default
spec:
  severity: 5
  message: "Zero-trust policy violation in wisecow"
  selector:
    matchLabels:
      app: wisecow

  # Allowed process executables
  process:
    matchPaths:
      - path: /app/wisecow.sh        # main script
      - path: /bin/bash
      - path: /bin/sh
      - path: /usr/bin/perl          # perl interpreter
      - path: /usr/games/fortune     # fortune binary
      - path: /usr/games/cowsay      # cowsay binary
      - path: /usr/bin/nc
      - path: /usr/bin/nc.openbsd
      - path: /usr/bin/cat
      - path: /usr/bin/sleep

  # Allowed files/directories
  file:
    matchDirectories:
      - dir: /app/                   # app directory & FIFO
        recursive: true
        readOnly: false
      - dir: /usr/share/games/fortunes/  # fortune data files
        recursive: true
        readOnly: true
      - dir: /usr/games/           # games data files
        recursive: true
        readOnly: true
      - dir: /usr/share/perl/          # allow Perl standard libraries
        recursive: true
        readOnly: true
      - dir: /usr/share/cowsay/cows/
        recursive: true
        readOnly: true  

  # Allowed network protocols
  network:
    matchProtocols:
      - protocol: TCP
      - protocol: UDP

  # Action: allow all above
  action:
    Allow
