apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: zero-trust-wisecow
  namespace: default
spec:
  severity: 5
  message: "Zero-trust policy violation in wisecow"
  selector:
    matchLabels:
      app: wisecow

  # Allowed process executables
  process:
    matchPaths:
      - path: /app/wisecow.sh        # main script
      - path: /bin/bash
      - path: /bin/sh
      - path: /usr/bin/perl          # used to run cowsay/fortune
      - path: /usr/bin/nc
      - path: /usr/bin/nc.openbsd
      - path: /usr/bin/cat
      - path: /usr/bin/sleep
      # Allow all binaries inside /usr/games recursively
      - path: /usr/games
        recursive: true

  # Allowed files/directories
  file:
    matchDirectories:
      - dir: /app/                        # app directory
        recursive: true
        readOnly: false
      - dir: /usr/share/games/fortunes/   # fortune data files
        recursive: true
        readOnly: true

  # Allowed network protocols
  network:
    matchProtocols:
      - protocol: TCP
      - protocol: UDP

  # Action: allow all above
  action:
    Allow
