apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: zero-trust-wisecow
  namespace: default
spec:
  severity: 5
  message: "Zero-trust policy violation in wisecow"
  selector:
    matchLabels:
      app: wisecow
  process:
    matchPaths:
      - path: /app/wisecow.sh       # main script
      - path: /usr/games/fortune    # fortune program
      - path: /usr/games/cowsay     # cowsay program
      - path: /usr/bin/nc           # netcat-openbsd
      - path: /usr/bin
  file:
    matchDirectories:a
      - dir: /app/
        recursive: true
        readOnly: false
    
  network:
    matchProtocols:
      - protocol: TCP
      - protocol: UDP   # needed for netcat if used with UDP
    
  action: Allow
