name: Wisecow CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  IMAGE_NAME: ${{ env.DOCKER_USERNAME }}/wisecow

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Get short SHA for tagging
      - name: Get short SHA
        id: vars
        run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.SHA }} .

      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ env.SHA }}

  edit-manifests:
    name: Edit Deployment Manifests
    runs-on: ubuntu-latest
    needs: build-and-push   # ensures this job runs after build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "IMAGE_NAME=${{ env.IMAGE_NAME }}" >> $GITHUB_ENV
          echo "SHA=${{ env.SHA }}" >> $GITHUB_ENV

      - name: Update deployment YAML
        run: |
          # Replace the placeholder in dep.yaml with the current image
          sed -i "s|image:.*|image: ${{ env.IMAGE_NAME }}:${{ env.SHA }}|" k8s/dep.yaml

          

     